services:
  postgres:
    image: postgres:16
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: postgrespw
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672

volumes:
  pgdata:
  mongodata:
